# Generated by Django 5.1.1 on 2025-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='price',
        ),
        migrations.AddField(
            model_name='painting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
