# Generated by Django 5.1.1 on 2025-02-27 22:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_painting_price_painting_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 27, 22, 9, 58, 86652, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
