# Generated by Django 5.1.1 on 2024-10-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='reply_message',
            new_name='reply',
        ),
    ]
